# Generated by Django 2.1.1 on 2018-09-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='friendslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makeName1', models.CharField(max_length=20)),
                ('makeName2', models.CharField(max_length=20)),
                ('songRecord', models.TextField(max_length=100)),
                ('makeType', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'friendslist',
            },
        ),
    ]
